apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hotel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: anastefanovska/hotel-booking-platform-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: hotel-config
                  key: DB_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: hotel-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: hotel-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hotel-secrets
                  key: MYSQL_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hotel-secrets
                  key: JWT_SECRET
